spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orclpdb1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=demotangerine
spring.datasource.password=tangerine

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.org.hibernate.envers.autoRegisterListeners=false

server.port=8081
server.servlet.context-path=/api
cache.capacity=5